added DMA to draw a frame without MCU core using
Gregor812/stm32-cmake pull request #5
Opened 2020-11-30 02:59 UTC by Gregor812

2020-12-01 09:06 UTC, lowsukuku requested changes
В целом всё круто, однако рекомендую обратить внимание на мои предложения.

2020-12-01 09:06 UTC, lowsukuku commented on display/ili9341.hpp
> +        DMA2_Stream6->M0AR = reinterpret_cast<uint32_t>((uint16_t *)_framebuffer);
Смесь C++ cast и С-cast не рекомендуется

2020-12-01 09:06 UTC, lowsukuku commented on display/ili9341.hpp
> +        _chipSelectPort->BSRR = (1 << (_chipSelectPin + 16));
пора бы это обернуть

2020-12-01 09:06 UTC, lowsukuku commented on main.cpp
> +        //Systick::DelayMilliseconds(150);
с этим надо попрощаться

2020-12-01 09:06 UTC, lowsukuku commented on main.cpp
> +    // DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;
с этим тоже

2020-12-01 09:06 UTC, lowsukuku commented on main.cpp
> +        auto color = Random::GetUint32() % 0x10000;
предлагаю заниматься подобными вычислениями внутри метода `uint32_t GetUint32(uint32_t min, uint32_t max);`

2020-12-01 09:06 UTC, lowsukuku commented on main.cpp
>  }
предлагаю вынести этот код в display/ili9341.hpp

2020-12-01 09:40 UTC, Gregor812 commented on display/ili9341.hpp
> +        DMA2_Stream6->M0AR = reinterpret_cast<uint32_t>((uint16_t *)_framebuffer);
Согласен, переделаю

2020-12-01 09:41 UTC, Gregor812 commented on display/ili9341.hpp
> +        _chipSelectPort->BSRR = (1 << (_chipSelectPin + 16));
Буду переделывать на IOutput, универсальный интерфейс. Это должно по идее скрыться за абстракцией

2020-12-01 09:42 UTC, Gregor812 commented on main.cpp
> +        //Systick::DelayMilliseconds(150);
Так точно

2020-12-01 09:42 UTC, Gregor812 commented on main.cpp
> +    // DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;
Так точно

2020-12-01 09:42 UTC, Gregor812 commented on main.cpp
> +        auto color = Random::GetUint32() % 0x10000;
Согласен, надо реализовать все методы как следует

2020-12-01 09:43 UTC, Gregor812 commented on main.cpp
>  }
Надеюсь, смогу нормально продумать, как всё это разместить внутри реализации IOutput

2020-12-02 05:30 UTC, lowsukuku approved these changes
Предлагаю решить вопрос с` Random::GetUint32`, пока не забыли, и закрывать PR

2020-12-02 05:30 UTC, lowsukuku commented on Random/Random.cpp
> +        return (GetValue() % (max - min)) + min;
Данное выражение не учитывает возможность integer overflow. Например: `GetUint32(100, std::numeric_limits<uint32_t>::max)` может вернуть значение `99 < min = 100`

2020-12-02 05:30 UTC, lowsukuku commented on main.cpp
> +            counter * DmaSendingSize;
нечто слабочитаемое, можно попробовать в будущем вынести этот расчёт в отдельный метод

2020-12-02 15:07 UTC, merged